# Generated by Django 5.2.6 on 2025-10-22 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_add_price_12h_24h_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Numele categoriei de articole (ex: Tehnici de Pescuit, Echipamente)",
                        max_length=100,
                        verbose_name="Numele categoriei",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Se generează automat din nume",
                        max_length=100,
                        unique=True,
                        verbose_name="URL slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrierea categoriei",
                        verbose_name="Descriere",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fas fa-fish",
                        help_text="Ex: fas fa-fish, fas fa-water",
                        max_length=50,
                        verbose_name="Clasa icon FontAwesome",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordinea de afișare (număr mai mic = mai sus)",
                        verbose_name="Ordine",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categorie articol",
                "verbose_name_plural": "Categorii articole",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="county",
            name="guide_content",
            field=models.TextField(
                blank=True,
                help_text="Ghid detaliat despre pescuitul în acest județ (acceptă HTML)",
                verbose_name="Ghid pescuit județ",
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="guide_excerpt",
            field=models.TextField(
                blank=True,
                help_text="Rezumat scurt al ghidului pentru județ",
                max_length=500,
                verbose_name="Rezumat ghid",
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="guide_title",
            field=models.CharField(
                blank=True,
                help_text="Titlul ghidului de pescuit pentru județ (ex: Ghid Complet Pescuit în Cluj)",
                max_length=250,
                verbose_name="Titlu ghid",
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="has_guide",
            field=models.BooleanField(
                default=False,
                help_text="Bifează dacă există un ghid de pescuit pentru acest județ",
                verbose_name="Are ghid",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="average_size",
            field=models.CharField(
                blank=True,
                help_text="Dimensiunea medie a speciei (ex: 30-50 cm)",
                max_length=100,
                verbose_name="Dimensiune medie",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="best_baits",
            field=models.TextField(
                blank=True,
                help_text="Cele mai eficiente momeli pentru această specie",
                verbose_name="Momeli recomandate",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="detailed_description",
            field=models.TextField(
                blank=True,
                help_text="Descriere completă a speciei (aspect, caracteristici, comportament)",
                verbose_name="Descriere detaliată",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="fishing_techniques",
            field=models.TextField(
                blank=True,
                help_text="Tehnici recomandate pentru pescuitul acestei specii",
                verbose_name="Tehnici de pescuit",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="habitat",
            field=models.TextField(
                blank=True,
                help_text="Informații despre habitatul preferat al speciei",
                verbose_name="Habitat",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Fotografie reprezentativă a speciei",
                null=True,
                upload_to="fish_species/",
                verbose_name="Imagine specie",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="legal_info",
            field=models.TextField(
                blank=True,
                help_text="Dimensiuni minime legale, perioade de prohibiție, etc.",
                verbose_name="Informații legale",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="max_size",
            field=models.CharField(
                blank=True,
                help_text="Dimensiunea maximă înregistrată (ex: 120 cm)",
                max_length=100,
                verbose_name="Dimensiune maximă",
            ),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Se generează automat din nume",
                max_length=100,
                unique=True,
                verbose_name="URL slug",
            ),
        ),
        migrations.AlterField(
            model_name="county",
            name="region",
            field=models.CharField(
                choices=[
                    ("MOLDOVA", "Moldova"),
                    ("MUNTENIA", "Muntenia"),
                    ("OLTENIA", "Oltenia"),
                    ("BANAT", "Banat"),
                    ("CRISANA", "Crișana"),
                    ("MARAMURES", "Maramureș"),
                    ("TRANSILVANIA", "Transilvania"),
                    ("DOBROGEA", "Dobrogea"),
                    ("BUCURESTI", "București"),
                ],
                help_text="Regiunea istorică din care face parte județului",
                max_length=50,
                verbose_name="Regiune",
            ),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titlul complet al articolului",
                        max_length=250,
                        verbose_name="Titlu articol",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Se generează automat din titlu",
                        max_length=250,
                        unique=True,
                        verbose_name="URL slug",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Rezumat scurt al articolului (max 500 caractere)",
                        max_length=500,
                        verbose_name="Rezumat",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Conținutul complet al articolului (acceptă HTML)",
                        verbose_name="Conținut",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imaginea principală a articolului",
                        null=True,
                        upload_to="articles/",
                        verbose_name="Imagine principală",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        default="Echipa Răsfățul Pescarului",
                        help_text="Numele care apare ca autor pe articol",
                        max_length=100,
                        verbose_name="Nume autor afișat",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Bifează pentru a publica articolul",
                        verbose_name="Publicat",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Articol recomandat (apare în secțiuni speciale)",
                        verbose_name="Recomandat",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Numărul de vizualizări al articolului",
                        verbose_name="Vizualizări",
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Timpul estimat de citire în minute",
                        verbose_name="Timp de citire (minute)",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data și ora când articolul a fost publicat",
                        null=True,
                        verbose_name="Data publicării",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data creării"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data actualizării"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Descriere pentru motoarele de căutare (max 160 caractere)",
                        max_length=160,
                        verbose_name="Meta descriere SEO",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Cuvinte cheie separate prin virgulă",
                        max_length=250,
                        verbose_name="Meta keywords SEO",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Autorul articolului",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Categoria din care face parte articolul",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="main.articlecategory",
                        verbose_name="Categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Articol",
                "verbose_name_plural": "Articole",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FishingTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="Termenul pescăresc (ex: Feeder, Boilies, Catch & Release)",
                        max_length=200,
                        unique=True,
                        verbose_name="Termen",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "definition",
                    models.TextField(
                        help_text="Definiția completă a termenului",
                        verbose_name="Definiție",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("equipment", "Echipamente"),
                            ("techniques", "Tehnici"),
                            ("species", "Specii"),
                            ("regulations", "Regulamente"),
                            ("general", "Termeni Generali"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Categorie",
                    ),
                ),
                (
                    "example_usage",
                    models.TextField(
                        blank=True,
                        help_text="Exemplu de utilizare a termenului în context",
                        verbose_name="Exemplu de utilizare",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_terms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Alți termeni legați de acesta",
                        to="main.fishingterm",
                        verbose_name="Termeni relevanți",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termen pescăresc",
                "verbose_name_plural": "Termeni pescărești",
                "ordering": ["term"],
            },
        ),
    ]
